parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  browser: true
  jest: true
extends:
  - 'eslint:recommended'
  - 'airbnb'
  - 'prettier'
  - 'prettier/react'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  arrow-parens:
    - error
    - always
  max-len:
    - error
    - code: 120
  # 以下规则完全信任prettier的输出
  comma-dangle: off
  react/sort-comp: off
  function-paren-newline: off
  object-curly-newline: off
  no-confusing-arrow: off
settings:
  'import/resolver':
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
